"""
Core data models for the trading bot.

This module defines the primary data structures used throughout the application,
such as Bar, Signal, and Trade data. Using Pydantic models ensures data
validation and consistency.
"""
from datetime import datetime
from enum import Enum
from pydantic import BaseModel
from typing import Optional

class Bar(BaseModel):
    """
    Represents a single bar of price data (OHLCV).
    """
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int

class SignalType(str, Enum):
    """
    The type of signal generated by a strategy.
    """
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"

class Signal(BaseModel):
    """
    Represents a trading signal generated by a strategy.
    """
    timestamp: datetime
    symbol: str
    signal_type: SignalType
    strategy: str
    price: Optional[float] = None

class OrderType(str, Enum):
    """
    The type of order to be placed.
    """
    MKT = "MKT"
    LMT = "LMT"
    STP = "STP"
    STP_LMT = "STP LMT"

class OrderAction(str, Enum):
    """
    The action to be taken for an order.
    """
    BUY = "BUY"
    SELL = "SELL"

class OrderStatus(str, Enum):
    """
    The status of an order.
    """
    PENDING = "Pending"
    SUBMITTED = "Submitted"
    FILLED = "Filled"
    CANCELLED = "Cancelled"
    REJECTED = "Rejected"

class Order(BaseModel):
    """
    Represents an order to be sent to the broker.
    """
    order_id: Optional[int] = None
    timestamp: datetime
    symbol: str
    action: OrderAction
    order_type: OrderType
    quantity: float
    limit_price: Optional[float] = None
    stop_price: Optional[float] = None
    status: OrderStatus = OrderStatus.PENDING
